config/routes.rb
Rails.application.routes.draw do

  resources :pins
  
  devise_for :users
  
  root 'pins#index'
  
  get 'about' => 'pages#about'
  get 'pins' => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :lockable, :timeoutable


  has_many :pins, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show], unless: :admin

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find(params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:image, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">




    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div> 
        <a href="/"><img src="/assets/blue_pin_white.jpg" alt="Home" title="Go to the home page" id="navbarLogo" /></a>
        <a class="navbar-brand" href="/">Let's Pin</a>
      </div>
    </div>




    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span>
          Home
          <% end %> </li>
          <li><%= link_to"About", about_path %></li>
          
          <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus-sign"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Let's Pin</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Let's Pin!</h1>

		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>

</div>

app/views/pages/about.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title">
			<h1>About Me</h1>
		</div>
	</div>
	<div class="panel-body">
		<h4>Forrest Meade</h4>
		<h5>&nbsp;&nbsp;&nbsp;Software Developer</h5>
		<br />
		<p>Hi, My name is Forrest Meade.  I am a Software Developer at Radford University.  I enjoy creating side applications to learn different languages, such as this application to learn RoR. My favorite developing environment is a dual montitor PC with soft ass chair running Ubuntu. I use Sublime text with google chrome and the terminal at the moment. I like to make quick changes with Vim.  Lastly, I like to think I am the master of git but im not.  I feel I am decent at it though.</p>
		<br />
		<h5>Known Programming Languages</h5>
		<ul>
			<li>Java</li>
			<li>Ruby on Rails</li>
			<li>Ada</li>
			<li>Python</li>
			<li>HTML</li>
			<li>CSS</li>
			<li>Javascript</li>
			<li>PHP</li>
		</ul>
		<br />

		<h5>Other Known Skills</h5>
		<ul>
			<li>Git</li>
			<li>Linux Shell</li>
			<li>Google Docs</li>
			<li>Fast development and learning</li>
			<li>Personal Management</li>
			<li>Time Management</li>
		</ul>
	</div>
	<div class="panel-footer">
		<%= link_to root_path do %>
				<span class="glyphicon glyphicon-home"></span>
				Home
				<% end %> &nbsp; | &nbsp;
				<a href="mailto:meadeforrest@gmail.com">Contact</a>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>

	<% if user_signed_in? %>

	<p>
		<%= link_to "Start Pinning", pins_path, class: "btn btn-primary btn-lg" %>
	</p>

	<% else %>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  <% end %>

</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
  <div class="box panel panel-default">
    <%= link_to image_tag(pin.image.url(:medium)), pin %>
    <div class="panel-body">
      <%= pin.description %>
      <br />
      <strong><%= pin.user.name if pin.user %></strong>

      <% if current_user && pin.user == current_user %>
      <div class="actions">
       <%= link_to edit_pin_path(pin) do %>
       <span class="glyphicon glyphicon-edit"></span>
       Edit
       <% end %>
       <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
       <span class="glyphicon glyphicon-trash"></span>
       Delete
       <% end %>
     </div>
     <% end %>
   </div>
 </div>
 <% end %>
</div>

<div class="center">
 <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>

			<div class="panel-body">
				<p><%= @pin.description %></p>
				<p><strong><%= @pin.user.name if @pin.user %></strong></p>
			</div>

			<div class="panel-footer">
				<% if current_user && @pin.user == current_user %>
				<%= link_to edit_pin_path(@pin) do %>
				<span class="glyphicon glyphicon-edit"></span>
				Edit
				<% end %> | 
				<% end %>
				<%= link_to 'Back', pins_path %>
			</div>
		</div>
	</div>
</div>